#!/usr/bin/env python3
"""Generate a minimal HapM (Hap Q Alpha) dual-texture MOV fixture.

ffmpeg cannot encode HapM, and (unlike Hap7) there is no committed real-file
fixture at all yet: the canonical encoder is the Vidvox AVF Batch Exporter
(macOS GUI, see tests/fixtures/README.md), which is not scriptable or
available in CI. This script produces a structurally valid MOV with a HapM
stsd entry and a real HapM frame -- a top-level Multi-Image section (type
0x0D) wrapping two ordinary sections back to back: a Scaled YCoCg DXT5
texture (format nibble 0xF) and an A_RGTC1/BC4 alpha texture (format nibble
0x1). This is sufficient to prove the highest-risk HapM-specific path: the
demuxer/decoder decoding *two* independent textures out of one sample
instead of just the first (the exact regression the reference Unity plugin
shipped).

Both texture sections use the None compressor (type nibble 0xA), matching
generate_hap7_fixture.py's choice -- this environment has no python-snappy
available, and the decoder's None path is fully supported, so there is no
loss of coverage for the demux/section-walking logic under test. Texture
bytes are deterministic pseudo-random data (fixed seed), not meaningful
compressed images -- as with the Hap7 fixture, the demuxer/decoder treat
them as opaque pass-through data, which is exactly what this fixture
validates. The two textures use different seeds so a decode that
accidentally aliased their output buffers would show up as a byte
mismatch rather than an accidental match.

Usage: python3 scripts/generate_hapm_fixture.py [output_path] [width] [height]
Default output: tests/fixtures/hapm.mov
Default dimensions: 640x360 (matches the other fixtures generated by
scripts/generate_fixtures.sh).

Also writes golden reference files alongside the .mov (same directory,
derived from the output path's stem): `<stem>_golden_tex0.bin` (color,
YCoCg DXT5) and `<stem>_golden_tex1.bin` (alpha, A_RGTC1) -- the raw texture
bytes for frame 0, byte-identical to what the None-compressor decode path
produces.
"""

import os
import random
import struct
import sys


def be32(v):
    return struct.pack(">I", v)


def be16(v):
    return struct.pack(">H", v)


def box(box_type, payload):
    return be32(8 + len(payload)) + box_type + payload


def fullbox(box_type, version, flags, payload):
    return box(box_type, be32((version << 24) | flags) + payload)


def make_ftyp():
    return box(b"ftyp", b"qt  " + be32(0) + b"qt  ")


def make_mvhd():
    body = (
        b"\x00" * 4   # creation_time
        + b"\x00" * 4  # modification_time
        + be32(30)     # timescale
        + be32(60)     # duration (2 seconds at 30fps)
        + b"\x00\x01\x00\x00"  # preferred rate 1.0
        + b"\x01\x00"  # preferred volume 1.0
        + b"\x00" * 10  # reserved
        + b"\x00\x01\x00\x00" * 3  # matrix identity (row 0)
        + b"\x00\x00\x00\x00"
        + b"\x00\x00\x00\x00\x01\x00\x00\x00" * 2 + b"\x00\x00\x00\x00"  # rows 1,2
        + b"\x00" * 24  # pre_defined
    )
    return fullbox(b"mvhd", 0, 0, body)


def make_tkhd(width, height):
    body = (
        b"\x00" * 4   # creation_time
        + b"\x00" * 4  # modification_time
        + be32(1)      # track_ID
        + b"\x00" * 4  # reserved
        + be32(60)     # duration
        + b"\x00" * 8  # reserved
        + b"\x00" * 2  # layer
        + b"\x00" * 2  # alternate_group
        + b"\x00\x00"  # volume (0 for video)
        + b"\x00\x00"  # reserved
        + b"\x00\x01\x00\x00"  # matrix row 0
        + b"\x00\x00\x00\x00"
        + b"\x00\x00\x00\x00\x01\x00\x00\x00"  # row 1
        + b"\x00\x00\x00\x00"
        + b"\x00\x00\x00\x00\x01\x00\x00\x00"  # row 2
        + be32(width << 16)   # width (fixed-point 16.16)
        + be32(height << 16)  # height (fixed-point 16.16)
    )
    return fullbox(b"tkhd", 0, 0x03, body)  # flags=3 (track_enabled | track_in_movie)


def make_mdhd():
    body = (
        b"\x00" * 4   # creation_time
        + b"\x00" * 4  # modification_time
        + be32(30)     # timescale
        + be32(60)     # duration
        + be16(0x55C4)  # language (undetermined)
        + be16(0)      # quality
    )
    return fullbox(b"mdhd", 0, 0, body)


def make_hdlr():
    body = (
        b"\x00" * 4   # pre_defined
        + b"vide"     # handler_type
        + b"\x00" * 12  # reserved
        + b"VideoHandler\x00"  # name
    )
    return fullbox(b"hdlr", 0, 0, body)


def make_vmhd():
    body = be16(0) + b"\x00" * 6  # graphicsmode + opcolor
    return fullbox(b"vmhd", 0, 1, body)


def make_dref():
    self_ref = box(b"url ", be32(1))  # flag=1 (self-contained)
    return fullbox(b"dinf", 0, 0, box(b"dref", be32(0) + be32(1) + self_ref))


def make_stsd_hapm(width, height):
    """Build a stsd box with one HapM VisualSampleEntry."""
    entry_payload = (
        b"\x00" * 6   # reserved (6)
        + be16(1)      # data_reference_index
        + be16(0) + be16(0)  # pre_defined + reserved
        + b"\x00" * 12  # pre_defined (12)
        + be16(width)
        + be16(height)
        + be32(0x00480000)  # horizresolution (72 dpi)
        + be32(0x00480000)  # vertresolution (72 dpi)
        + be32(0)           # reserved
        + be16(1)           # frame_count
        + b"\x00" * 32     # compressorname (32)
        + be16(0x0018)      # depth (24-bit)
        + be16(0xFFFF)      # color_table_id
    )
    entry = box(b"HapM", entry_payload)
    return fullbox(b"stsd", 0, 0, be32(1) + entry)


def make_stts(frame_count):
    body = be32(1) + be32(frame_count) + be32(1)
    return fullbox(b"stts", 0, 0, body)


def make_stsz(sample_size, sample_count):
    body = be32(sample_size) + be32(sample_count)
    if sample_size == 0:
        body += b"".join(be32(0) for _ in range(sample_count))
    return fullbox(b"stsz", 0, 0, body)


def make_stsc(sample_count):
    body = be32(1) + be32(1) + be32(sample_count) + be32(1)
    return fullbox(b"stsc", 0, 0, body)


def make_stco(offset):
    body = be32(1) + be32(offset)
    return fullbox(b"stco", 0, 0, body)


def make_section(type_byte, payload):
    """A single Hap section: 3-byte LE size + 1 type byte + payload (the
    plain 4-byte header form; our payloads are always well under 16 MB)."""
    length = len(payload)
    assert length < (1 << 24), "payload too large for the 4-byte section header"
    header = bytes([length & 0xFF, (length >> 8) & 0xFF, (length >> 16) & 0xFF, type_byte])
    return header + payload


# Compressor nibbles (high nibble of a texture section's type byte).
COMPRESSOR_NONE = 0xA

# Format nibbles (low nibble of a texture section's type byte).
FORMAT_YCOCG_DXT5 = 0xF
FORMAT_A_RGTC1 = 0x1

# Top-level Multi-Image (HapM) section type byte -- not a compressor|format
# pair, this whole byte identifies the container.
SECTION_MULTI_IMAGE = 0x0D


def make_texture_data(width, height, block_size, seed):
    """Deterministic pseudo-random compressed-texture bytes: `block_size`
    bytes per 4x4 block, covering the full width x height grid (rounded up
    to whole blocks, matching the Hap spec's block layout)."""
    blocks_x = (width + 3) // 4
    blocks_y = (height + 3) // 4
    total = blocks_x * blocks_y * block_size
    rng = random.Random(seed)
    return bytes(rng.getrandbits(8) for _ in range(total))


def make_hapm_frame(width, height):
    """Build a single HapM frame: a Multi-Image (0x0D) section wrapping the
    color (YCoCg DXT5) section followed by the alpha (A_RGTC1) section --
    the conventional HapM order. Both sub-sections use the None compressor.

    Returns (frame_bytes, color_data, alpha_data) so the caller can also
    emit golden reference files from the same source bytes.
    """
    color_data = make_texture_data(width, height, 16, seed=0xC0106)  # DXT5: 16 B/block
    alpha_data = make_texture_data(width, height, 8, seed=0xA17A5)  # RGTC1/BC4: 8 B/block

    color_section = make_section((COMPRESSOR_NONE << 4) | FORMAT_YCOCG_DXT5, color_data)
    alpha_section = make_section((COMPRESSOR_NONE << 4) | FORMAT_A_RGTC1, alpha_data)

    body = color_section + alpha_section
    frame = make_section(SECTION_MULTI_IMAGE, body)
    return frame, color_data, alpha_data


def build_hapm_mov(width=640, height=360):
    frame_data, color_data, alpha_data = make_hapm_frame(width, height)

    stsd = make_stsd_hapm(width, height)
    stts = make_stts(1)
    stsz = make_stsz(len(frame_data), 1)
    stsc = make_stsc(1)

    ftyp = make_ftyp()

    # Two passes: the stco offset depends on moov's size, which is fixed
    # once stco itself is built with any offset (stco's payload size never
    # changes), so a single fixup pass suffices (matches
    # generate_hap7_fixture.py's approach).
    stco = make_stco(0)
    stbl = box(b"stbl", stsd + stts + stsz + stsc + stco)
    minf = box(b"minf", make_vmhd() + make_dref() + stbl)
    mdia = box(b"mdia", make_mdhd() + make_hdlr() + minf)
    trak = box(b"trak", make_tkhd(width, height) + mdia)
    moov = box(b"moov", make_mvhd() + trak)

    mdat_data_offset = len(ftyp) + len(moov) + 8

    stco = make_stco(mdat_data_offset)
    stbl = box(b"stbl", stsd + stts + stsz + stsc + stco)
    minf = box(b"minf", make_vmhd() + make_dref() + stbl)
    mdia = box(b"mdia", make_mdhd() + make_hdlr() + minf)
    trak = box(b"trak", make_tkhd(width, height) + mdia)
    moov = box(b"moov", make_mvhd() + trak)

    mdat = box(b"mdat", frame_data)
    return ftyp + moov + mdat, color_data, alpha_data


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "tests/fixtures/hapm.mov"
    width = int(sys.argv[2]) if len(sys.argv) > 2 else 640
    height = int(sys.argv[3]) if len(sys.argv) > 3 else 360

    data, color_data, alpha_data = build_hapm_mov(width=width, height=height)

    out_dir = os.path.dirname(out_path) or "."
    os.makedirs(out_dir, exist_ok=True)
    with open(out_path, "wb") as f:
        f.write(data)
    print(f"Generated {out_path} ({len(data)} bytes)")

    stem = os.path.splitext(os.path.basename(out_path))[0]
    tex0_path = os.path.join(out_dir, f"{stem}_golden_tex0.bin")
    tex1_path = os.path.join(out_dir, f"{stem}_golden_tex1.bin")
    with open(tex0_path, "wb") as f:
        f.write(color_data)
    with open(tex1_path, "wb") as f:
        f.write(alpha_data)
    print(f"Generated {tex0_path} ({len(color_data)} bytes)")
    print(f"Generated {tex1_path} ({len(alpha_data)} bytes)")


if __name__ == "__main__":
    main()
